import { SlotSymbol } from '../../types/slot';

export const symbols: SlotSymbol[] = [
  {
    id: 'apple',
    name: 'Apple',
    image: 'pixi/assets/symbols/apple.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'cake',
    name: 'Cake',
    image: 'pixi/assets/symbols/cake.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'candy-cane',
    name: 'Candy-cane',
    image: 'pixi/assets/symbols/candy-cane.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'candy',
    name: 'Candy',
    image: 'pixi/assets/symbols/candy.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'croissant',
    name: 'Croissant',
    image: 'pixi/assets/symbols/croissant.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'diamond',
    name: 'Diamond',
    image: 'pixi/assets/symbols/diamond.png',
    type: 'bonus',
    weight: 1,
  },
  {
    id: 'dollar',
    name: 'Dollar',
    image: 'pixi/assets/symbols/dollar.png',
    type: 'wild',
    weight: 1,
  },
  {
    id: 'donut',
    name: 'Donut',
    image: 'pixi/assets/symbols/donut.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'lollipop',
    name: 'Lollipop',
    image: 'pixi/assets/symbols/lollipop.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'muffin',
    name: 'Muffin',
    image: 'pixi/assets/symbols/muffin.png',
    type: 'regular',
    weight: 1,
  },
  {
    id: 'sweet',
    name: 'Sweet',
    image: 'pixi/assets/symbols/sweet.png',
    type: 'regular',
    weight: 1,
  },
];
